spring.application.name=TechnicalTest

spring.datasource.url=jdbc:mysql://localhost:3306/technical_test_db
os?useSSL=false&serverTimezone=UTC 
spring.datasource.username=root 
spring.datasource.password=Rafobravo01@ 
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver 

#Spring Data JPA Configuration
spring.jpa.show-sql=true 

#Spring Data JPA Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.open-in-view=true 
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.My
SQLDialect
documentation.application.version=${project.version} 
documentation.application.description=${project.description} 